### ISSUE TITLE
Tomee-esports logo issue

### ISSUE THREAD

**Issue by FastMinion** [KapocsiH/IKT-2#11]
Ha olvasol egy hírt akkor ugyanabban a directory-ban próbálja meg betölteni az index.html-t, miután rányomsz bal felül a Tomee-Esports "logóra"

**Comment by HUNBenjamin** [comment]
Kedves Horváth "Minyon" Márk!
Köszönjük szépen a részletes kielemzést. Magabiztossággal kijelenthetem, hogy a probléma megoldásra került.

**Comment by FastMinion** [comment]
Köszönöm szépen a gyorsan történt probléma megoldását!
További szép napot kívánok Mr. Reinhardt "HUNBenjamin" Benjamin!
**Üdvözlettel:**
Horváth "Minyon" Márk
